name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome to GHA
              run: echo Welcome to GHA
            
            - name: List the files
              run: ls

            - name: Read the file
              run: cat README.md