name: Generate ASCII Artwork

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: List the files
              run: ls -altr
              
            - name: Executing the Script
              run: ./ascii-script.sh