name: Generate ASCII Artwork

on: 
    push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay
              run: sudo apt-get install cowsay -y

            - name: Execute Cowsay
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v3
              with:
                name: dragon-file-artifact
                path: dragon.txt


    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
            - name: Download Build Artifact
              uses: actions/download-artifact@v3
              with:
                name: dragon-file-artifact
                path: dragon.txt

            - name: Test file exists
              run: grep -i "dragon" dragon.txt

    deploy_job_3:
        needs: [test_job_2]
        runs-on: ubuntu-latest
        steps:
            - name: Download Build Artifact
              uses: actions/download-artifact@v3
              with:
                name: dragon-file-artifact
                path: dragon.txt

            - name: Read file
              run: cat dragon.txt

            - name: Deploy
              run: echo Deploy...
